### ISSUE TITLE
the genetree-vis is not showing the representatives

### ISSUE THREAD

**Issue by ajo2995** [warelab/gramoogle#125]
GRMZM2G462417 - arabidopsis rep is not displayed on release50 build
http://brie/gramene-search/release50/#%7B%22id:GRMZM2G462417%22:%7B%22category%22:%22Gene%22,%22display_name%22:%22GRMZM2G462417%22,%22fq%22:%22id:GRMZM2G462417%22%7D%7D

but is shown on dev build
http://brie/gramene-search/dev/#%7B%22id:GRMZM2G462417%22:%7B%22category%22:%22Gene%22,%22display_name%22:%22GRMZM2G462417%22,%22fq%22:%22id:GRMZM2G462417%22%7D%7D

**Comment by mycrobe** [comment]
I bet this is more fallout from warelab/gramene-mongodb#36

**Comment by ajo2995** [comment]
probably because representative is a subdoc of gene_tree now.

**Comment by mycrobe** [comment]
I think that the commit referenced above may have fixed this issue a week before it was reported. Forgot to `git push` it.

**Comment by mycrobe** [comment]
No, that issue is unrelated. There are currently no representative genes in the release50 database.

**Comment by mycrobe** [comment]
For example: http://devdata.gramene.org/v50/genes?idList=AT3G52430

**Comment by mycrobe** [comment]
Oh dear. Another silly error on my part: There are no representative genes for Arabidopsis thaliana!

**Comment by mycrobe** [comment]
Now we wait for the travis build to deploy to http://brie.cshl.edu/gramene-search/release50
