### ISSUE TITLE
Add expression image from Araport

### ISSUE THREAD

**Issue by mycrobe** [warelab/gramoogle#126]
Look at the [AraPort page for PAD4](https://apps.araport.org/thalemine/report.do?id=1061904&trail=|1061904). Scroll down to find "eFP expression"

This is just an image, [that is available from the AraPort API](https://api.araport.org/data/BioAnalyticResource/efp_service/pr2-0.1/?request={%22agi%22:%22AT3G52430%22,%22datasource%22:%22Developmental_Map%22})

We should consider including it in Gramoogle with the ATLAS data, unless politics.

**Comment by ajo2995** [comment]
using ATLAS widget instead
