### ISSUE TITLE
Redesign and standardize result details

### ISSUE THREAD

**Issue by mycrobe** [warelab/gramoogle#130]
The result details, e.g. Location, Homology, etc., do not have consistent user interfaces. These need to be rethought. There are common elements to each of these views, e.g. a visualization, a description, query modifiers, and links to other parts of Gramene.

**Comment by mycrobe** [comment]
I've moved this to release 50 because it would be more work to add features to the details tabs and *then* refactor the UX, rather than refactor them all first.

**Comment by mycrobe** [comment]
I don't propose radical change, just clear separation of the detail information, and other actions:

![result detail](https://cloud.githubusercontent.com/assets/40182/13860811/93343948-ec60-11e5-8d5d-deb55c48d23a.png)

**Comment by mycrobe** [comment]
Notes:
* Maximum of 4 links to modifying the global search state 
  * ("Explore Gramene")
  * Not sure if this is best language.
* Interacting with "The Thing" should only change the thing, and not the global search state.
  * Prevent unwanted surprises.
  * However, "The Thing" can have state that the rest of the detail can see, e.g. something is selected
     * This can change the behaviour of "Explore Gramene" links, etc.
     * (this is more obvious when you see a concrete example; see next image)
* Big box around vis is optional, but some visual separation between the detailed information and stuff you can do with it is not.
* What if there are multiple Things? 
  * Show them together when related
  * They should be in separate tabs if they're not related

**Comment by mycrobe** [comment]
Concrete example for homology:

![homology](https://cloud.githubusercontent.com/assets/40182/13861053/a4e4e3d0-ec61-11e5-9a99-7a8584cd71e1.png)

**Comment by mycrobe** [comment]
Concrete example for homology:

![homology](https://cloud.githubusercontent.com/assets/40182/13861076/c976d0f0-ec61-11e5-961c-d7985c56f131.png)

**Comment by ajo2995** [comment]
I think "show orthologs in" doesn't need to have the select box next to it. It could display a popover(?) where you can select multiple species with checkboxes.

**Comment by mycrobe** [comment]
@ajo2995 so the link would say "show orthologs" and then another dialog would appear, with options like
* all species
* `[ multiple select box | v ]`

**Comment by ajo2995** [comment]
The tree view should update while the dialog is still open as soon as species are (un)checked.

**Comment by mycrobe** [comment]
I've mocked up Location and Transcript, and I'm fairly happy with the results. The [balsamiq file is here](https://drive.google.com/file/d/0B1ztWq-u5dPpRlJEZGZrNXc2WTA/view?usp=sharing)

**Comment by mycrobe** [comment]
![location](https://cloud.githubusercontent.com/assets/40182/13888393/9a98de34-ed17-11e5-996d-f7c4b0ee8e1d.png)
![transcript](https://cloud.githubusercontent.com/assets/40182/13888392/9a98770a-ed17-11e5-9389-4d65e4611cda.png)

**Comment by mycrobe** [comment]
Mobile: 
![mobile](https://cloud.githubusercontent.com/assets/40182/13888537/45c5a724-ed18-11e5-9e25-deb50fdaff55.png)

**Comment by mycrobe** [comment]
Im mobile, the "View options" panel would EITHER be minfied and would expand on touch, OR be hidden entirely.

**Comment by mycrobe** [comment]
I'm going to consider this design work "done" and will lay out the implementation tasks now.

**Comment by ajo2995** [comment]
Another view option on the gene tree should be to display/hide a multiple sequence alignment (the sequences and cigar strings are in the tree). Showing the MSA would make The Thing much wider. In that case view options can get minified.
