### ISSUE TITLE
GRMZM2G104843 does not show up as part of jasmonic acid biosynthesis pathway

### ISSUE THREAD

**Issue by mycrobe** [warelab/gramoogle#131]
According to [Plant Reactome](http://plantreactome.gramene.org/PathwayBrowser/#SPECIES=6951903&DIAGRAM=6957159&ID=6952120&PATH=6957147,6957146,6957157&DTAB=MT), GRMZM2G104843 is part of jasmonic acid biosynthesis. 

However, it's not in [this list of jasmonic genes](http://brie/gramene-search/reactome-img/#%7B%22pathways__ancestors:1119332%22:%7B%22category%22:%22Plant%20Reactome%22,%22display_name%22:%22jasmonic%20acid%20biosynthesis%22,%22fq%22:%22pathways__ancestors:1119332%22%7D,%22taxonomy__ancestors:4577%22:%7B%22category%22:%22Taxonomy%22,%22display_name%22:%22Zea%20mays%22,%22fq%22:%22taxonomy__ancestors:4577%22%7D%7D), and does [not show pathway information in its result view](http://brie/gramene-search/reactome-img/#%7B%22id:GRMZM2G104843%22:%7B%22category%22:%22Gene%22,%22display_name%22:%22GRMZM2G104843%22,%22fq%22:%22id:GRMZM2G104843%22%7D%7D).

Marcela has reported that @preecej is dealing with a related issue in Reactome Search.

Acceptance Criteria: Pathway details view shows up for GRMZM2G104843, and GRMZM2G104843 is in the result list for jasmonic acid biosynthesis pathway.

**Comment by preecej** [comment]
Noted. Working on it.

**Comment by mycrobe** [comment]
@preecej is this a plant reactome issue?

**Comment by preecej** [comment]
It's both Plant Reactome search (maize) and Gramene search (an indexing 
issue?). Marcela put both sites' issues in one ticket.

I'm working on fixing the search interface in Plant Reactome, then I'll 
need to give you & Andrew a new index dump. At that point, we should see 
if there is something in the formatting of Gramene's data load that is 
also causing issues, b/c tools.gramene.org takes users to the PR search 
results page, when it should be linking directly to pathway diagrams.

- j

**Comment by mycrobe** [comment]
Could you please add links to the tickets you mentioned in this one? 

Thanks!

**Comment by mycrobe** [comment]
The resolution here is to wait for updated data with Release 51.
