### ISSUE TITLE
genomes of interest: configure

### ISSUE THREAD

**Issue by ajo2995** [warelab/gramoogle#142]
Create a user interface component to allow the user to customize the genomes of interest.

It should display the fully expanded species tree with checkboxes by the leaf nodes. The genomes of interest correspond to checked boxes. Clicking on internal nodes can let the user select all/none of the genomes in the subtree.

There needs to be a button somewhere in the search bar to let the user launch this component.
(search: 46/46 genomes) - all genomes
(search: 12/46 genomes) - customized set of 12 genomes of interest

see also #141

**Comment by ajo2995** [comment]
This might become part of an overall configuration component, but I can't think of anything else to configure at this time.

**Comment by mycrobe** [comment]
Currently this is implemented as a list of genomes: 
<img width="288" alt="screen shot 2016-05-27 at 11 37 35 am" src="https://cloud.githubusercontent.com/assets/40182/15613029/6ed79690-23ff-11e6-890c-9d016cf6eb7a.png">
