### ISSUE TITLE
wide selection leads to enormous query

### ISSUE THREAD

**Issue by ajo2995** [warelab/gramoogle#145]
Since the selection filter enumerates the bins that are within the selected region, the query can become unacceptably large for the server (414 Request-URL Too Large).

The filter should be reformatted to a set of non-overlapping ranges `fq=fixed_1000__bin:(28008 TO 29007)`

**Comment by mycrobe** [comment]
http://devdata.gramene.org/v50/search?fq=fixed_1000__bin%3A(28008%20TO%2029007) returns an error
