### ISSUE TITLE
Add pathway image to result details

### ISSUE THREAD

**Issue by mycrobe** [warelab/gramoogle#99]
Plant reactome has an API that returns an image of a pathway. We should use that.

**Comment by ajo2995** [comment]
documentation of the reactome rest service:
http://www.reactome.org/pages/documentation/developer-guide/restful-service/
use http://data.gramene.org/reactome as the baseUrl

**Comment by mycrobe** [comment]
Examples of how to use the API to get an image here: https://tonicdev.com/mycrobe/reactome-pathway-image

Note that I haven't figured out how to highlight a blob in the pathway yet.

**Comment by mycrobe** [comment]
I threw together a prototype that uses a react component to do the asynchronous call to the reactome API, but it does not work because the web service does not have CORS headers defined. :-1:

**Comment by mycrobe** [comment]
[As mentioned here](https://github.com/warelab/gramoogle/commit/ef133bca7d068eb9b6764c065190b3251b4dd6d6#comments)
> Potential quick solution would be to use apache to proxy this API to, say, `data.gramene.org/v50/reactome/highlightPathwayDiagram` and inject the appropriate CORS header.

**Comment by mycrobe** [comment]
However, proxying to that URI would be confusing because it wouldn't / couldn't be documented in swagger. Perhaps removing the v50 prefix would be better. Should check with Justin re: how they do API versioning.

**Comment by mycrobe** [comment]
@preecej added CORS to the dev server.

**Comment by mycrobe** [comment]
Moved to a later release to make way for #130
